import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserContextProvider from "./_context/UserContext";
import MyNavbar from "./_components/MyNavbar";
import { Toaster } from "react-hot-toast";
import NoteContextProvider from "./_context/NoteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Note App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider>
          <NoteContextProvider>
            <Toaster />
            <MyNavbar />
            {children}
          </NoteContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
